openapi: 3.0.1
info:
  title: Purplebricks Feedback API 1 - Core Squad
  description: '### Vertical slice for the Uber property-centric feedback endpoints

    ### [Purplebricks Feedback API Git Repository](https://dev.azure.com/purplebricks/BackEnd/_git/feedback-api)'
  version: '1'
servers:
- url: https://api.purplebricks.co.uk/feedback-api
paths:
  /v1/managefeedback/allpropertyfeedback/{propertyId}:
    get:
      tags:
      - ManageFeedback
      parameters:
      - name: propertyId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Purplebricks.Feedback.Business.Models.FeedbackSummaryViewModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Purplebricks.Feedback.Business.Models.FeedbackSummaryViewModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Purplebricks.Feedback.Business.Models.FeedbackSummaryViewModel'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
components:
  schemas:
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    Purplebricks.Feedback.Business.Models.FeedbackSummaryViewModel:
      type: object
      properties:
        bookingId:
          type: integer
          format: int32
        feedbackId:
          type: integer
          format: int32
          nullable: true
        userById:
          type: integer
          format: int32
          nullable: true
        userBy:
          type: string
          nullable: true
        userToId:
          type: integer
          format: int32
        userTo:
          type: string
          nullable: true
        eventDate:
          type: string
          format: date-time
        presentation:
          type: integer
          format: int32
          nullable: true
        suitability:
          type: integer
          format: int32
          nullable: true
        price:
          type: integer
          format: int32
          nullable: true
        cancellationComments:
          type: string
          nullable: true
        comments:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Authorization header using Bearer scheme
      name: Authorization
      in: header
security:
- Bearer: []
